### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by balbinosoares** [balbinosoares/relact-frontend#1]
**Prototype UX Design**

- [ ] Create the UX prototype using SAP Build - http://build.me
- [ ] Import the UX prototype in SAP WebIDE 

**Create Frontend**
**Admin**
- [ ] Manage Teams

**Team Member**
- [ ] Add Relevant activity(current and next week)
- [ ] Display relevant activity per week (previous, current and next) 

**Manger**
- [ ] View previous, current and next activities of you managed teams
- [ ] View monthly summary
